### ISSUE TITLE
[Question] Is Default() method syntax changed intentionally?  Is this correct if leaf has value other than string.

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#72]
In the latest master chekout, i see the following changes.

The return type of  Default() method for leafList is changed from []interface{} to []string . 
The return type of  Default() method for leaf is changed from interface{} to string . 
 Is this change intentional?????**
The type of the leaf can be any type,  it would not necessarilybe a string,

    func (m *LeafList) Default() []string {
	    return m.defaultVals
    }

**Comment by davidmat50** [comment]
ok.  Now i see a new method  DefaultValue()  got introduced.   i will use it.

**Comment by dhubler** [comment]
It was intentional.  One can argue both cases, I thought string would make
API more clear this is as it was defined in YANG.  When it is pre-coerced
to the surrounding type, you may have lost the original exact definition.
"4.00" v.s. "4".    The driver was serializing the YANG over grpc to
support python and needing a stable value.

If you have a good use case for the interface{}  we can always add
"DefaultVal() interface{}"

**Comment by dhubler** [comment]
ah, i guess i forgot i already added that ;)
